### ISSUE TITLE
Hello, could you please tell me how to run this code?

### ISSUE THREAD

**Issue by tuji-sjp** [dongyp13/Translation-Invariant-Attacks#1]
I run this code with "python attack_iter.py", and get the following error:

Caused by op 'save/RestoreV2', defined at:
  File "attack_iter.py", line 233, in <module>
    tf.app.run()
  File "/home/dl/lijiawei/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "attack_iter.py", line 213, in main
    s1 = tf.train.Saver(slim.get_model_variables(scope='InceptionV3'))
  File "/home/dl/lijiawei/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1284, in __init__
    self.build()
  File "/home/dl/lijiawei/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1296, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/dl/lijiawei/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1333, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/dl/lijiawei/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 781, in _build_internal
    restore_sequentially, reshape)
  File "/home/dl/lijiawei/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 400, in _AddRestoreOps
    restore_sequentially)
  File "/home/dl/lijiawei/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 832, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/dl/lijiawei/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1463, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/dl/lijiawei/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/dl/lijiawei/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/home/dl/lijiawei/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
         [[Node: save/RestoreV2/_301 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_306_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Could you please tell me how to run this code?
Thank you very much!

**Comment by dongyp13** [comment]
I've updated the readme about how to run the code.

**Comment by tuji-sjp** [comment]
> I've updated the readme about how to run the code.

Maybe I have to use python2.7? Can I run in python3.6?
I run this code with the command "bash run_attack.sh input_dir output_dir".
But there is still a mistake:

Traceback (most recent call last):
  File "attack_iter.py", line 233, in <module>
    tf.app.run()
  File "/home/jinping/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 119, in run
    argv = flags.FLAGS(_sys.argv if argv is None else argv, known_only=True)
  File "/home/jinping/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 112, in __call__
    return self.__dict__['__wrapped'].__call__(*args, **kwargs)
  File "/home/jinping/anaconda3/envs/py27/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 626, in __call__
    unknown_flags, unparsed_args = self._parse_args(args, known_only)
  File "/home/jinping/anaconda3/envs/py27/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 774, in _parse_args
    flag.parse(value)
  File "/home/jinping/anaconda3/envs/py27/lib/python2.7/site-packages/absl/flags/_flag.py", line 166, in parse
    self.value = self._parse(argument)
  File "/home/jinping/anaconda3/envs/py27/lib/python2.7/site-packages/absl/flags/_flag.py", line 184, in _parse
    'flag --%s=%s: %s' % (self.name, argument, e))
**absl.flags._exceptions.IllegalFlagValueError: flag --max_epsilon=: could not convert string to float:**

In addition, my file structure is as follows:
![image](https://user-images.githubusercontent.com/30012354/56505416-373b5300-654e-11e9-8b07-669603e48d02.png)

**Comment by dongyp13** [comment]
The structure is correct. But the size of the models should be larger than 100M. I did not try python 3. From the log, it seems that the error comes from the type of epsilon. You may convert the type and fix the errors.

**Comment by tuji-sjp** [comment]
> The structure is correct. But the size of the models should be larger than 100M. I did not try python 3. From the log, it seems that the error comes from the type of epsilon. You may convert the type and fix the errors.

Ok, but this new error is what I encountered on python2. I haven't done it in python3 either.

**Comment by dongyp13** [comment]
Oh, sorry. I forgot to specify the epsilon in the command. Now I update the running command.

**Comment by tuji-sjp** [comment]
> Oh, sorry. I forgot to specify the epsilon in the command. Now I update the running command.

Thank you, I will try it.

**Comment by tuji-sjp** [comment]
> Oh, sorry. I forgot to specify the epsilon in the command. Now I update the running command.

Is there a problem with the download link you gave to the models?
Each model file I downloaded was only 3kb in size. And reporting an error about the .ckpt file while running the program.

**Comment by dongyp13** [comment]
Maybe you can download them at the official link [https://github.com/tensorflow/models/tree/master/research/slim](https://github.com/tensorflow/models/tree/master/research/slim).

**Comment by tuji-sjp** [comment]
> Maybe you can download them at the official link https://github.com/tensorflow/models/tree/master/research/slim.

**I try it in python3.6, and get the error：**
Traceback (most recent call last):
  File "attack_iter.py", line 233, in <module>
    tf.app.run()
  File "/home/jinping/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 12                                                      5, in run
    _sys.exit(main(argv))
  File "attack_iter.py", line 225, in main
    for filenames, images in load_images(FLAGS.input_dir, batch_shape):
  File "attack_iter.py", line 87, in load_images
    image = imread(f, mode='RGB').astype(np.float) / 255.0
  File "/home/jinping/.local/lib/python3.6/site-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/home/jinping/anaconda3/lib/python3.6/site-packages/scipy/misc/pilutil.py", line 164, in imr                                                      ead
    im = Image.open(name)
  File "/home/jinping/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 2552, in open
    prefix = fp.read(16)
  File "/home/jinping/.local/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line                                                       132, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length, status))
  File "/home/jinping/.local/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line                                                       100, in _prepare_value
    return compat.as_str_any(val)
  File "/home/jinping/.local/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 107                                                      , in as_str_any
    return as_str(value)
  File "/home/jinping/.local/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 80,                                                       in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**So I change to use python2.7, solve it.
But there is a new problem:**
Traceback (most recent call last):
  File "attack_iter.py", line 233, in <module>
    tf.app.run()
  File "/home/jinping/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "attack_iter.py", line 225, in main
    for filenames, images in load_images(FLAGS.input_dir, batch_shape):
  File "attack_iter.py", line 89, in load_images
    images[idx, :, :, :] = image * 2.0 - 1.0
ValueError: could not broadcast input array from shape (600,800,3) into shape (299,299,3)

**Maybe the input image must be (299,299,3)?
Is there no uniform processing of input data in your code?**

**Comment by tuji-sjp** [comment]
> Maybe you can download them at the official link https://github.com/tensorflow/models/tree/master/research/slim.

I did use the official .ckpt files. It's ok.

**Comment by dongyp13** [comment]
Yes, the image size should be (299,299,3). We'll provide a pre-processing procedure later.

**Comment by tuji-sjp** [comment]
> Yes, the image size should be (299,299,3). We'll provide a pre-processing procedure later.

Thanks a lot!

**Comment by tuji-sjp** [comment]
> Yes, the image size should be (299,299,3). We'll provide a pre-processing procedure later.

Perhaps you have provided a unified pre-processing procedure？

**Comment by dongyp13** [comment]
Done

**Comment by qilong-zhang** [comment]
I use `py27` and `tf1.12` but I still get the error
```
2019-07-24 15:02:14.354548: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 77.06M (80805888 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
INFO:tensorflow:Restoring parameters from inception_v3.ckpt
2019-07-24 15:02:16.977459: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./inception_v3.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
2019-07-24 15:02:16.978749: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./inception_v3.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
2019-07-24 15:02:16.978854: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at save_restore_tensor.cc:170 : Data loss: Unable to open table file ./inception_v3.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file ./inception_v3.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "attack_iter.py", line 285, in <module>
    tf.app.run()
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "attack_iter.py", line 271, in main
    s1.restore(sess, FLAGS.checkpoint_path_inception_v3)
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1802, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file ./inception_v3.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "attack_iter.py", line 285, in <module>
    tf.app.run()
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "attack_iter.py", line 263, in main
    s1 = tf.train.Saver(slim.get_model_variables(scope='InceptionV3'))
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1338, in __init__
    self.build()
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1347, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1384, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 835, in _build_internal
    restore_sequentially, reshape)
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 472, in _AddRestoreOps
    restore_sequentially)
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 886, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1463, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/zhangqilong/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

DataLossError (see above for traceback): Unable to open table file ./inception_v3.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

```
and My struct is below
<img src="https://img-blog.csdnimg.cn/20190724150621570.png">
@dongyp13 Is there any wrong?  Thanks!
